# Generated by Django 4.1 on 2022-09-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NezrenaApp', '0013_auto_20211102_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupaccounting',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='groupaccounting',
            name='group_composition',
        ),
        migrations.RemoveField(
            model_name='groupaccounting',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='rentedequipment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='rentedequipment',
            name='group_accounting',
        ),
        migrations.RemoveField(
            model_name='rentedequipment',
            name='user_accounting',
        ),
        migrations.RemoveField(
            model_name='useraccounting',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='useraccounting',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='GroupAccounting',
        ),
        migrations.DeleteModel(
            name='GroupComposition',
        ),
        migrations.DeleteModel(
            name='RentedEquipment',
        ),
        migrations.DeleteModel(
            name='UserAccounting',
        ),
    ]
